---

apiVersion: v1
kind: Service
metadata:
  name: webapp-flask
  labels:
    app: webapp-flask
spec:
  ports:
  - name: metrics
    port: 8000
    targetPort: metrics
    protocol: TCP
  - name: app
    port: 5000
    targetPort: app
    protocol: TCP
  selector:
    app: webapp-flask

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-flask
  name: webapp-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-flask
  template:
    metadata:
      labels:
        app: webapp-flask
    spec:
      containers:
      - image: prometeheus-webapp-flask:latest
        name: prometheus-webapp-flask
        imagePullPolicy: Never
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "app"
        - name: MYSQL_DB
          value: "app"
        ports:
        - name: app
          containerPort: 5000
          protocol: TCP
        - name: metrics
          containerPort: 8000
          protocol: TCP
        command: ["/wait-for-it.sh", "mysql:3306", "--", "python", "./main.py"]
