server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://<DNS/IP>:<PORT>/loki/api/v1/push

scrape_configs:
- job_name: docker-containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: container-logs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag
        output: log

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"

  - regex:
      expression: (?P<levelname>(INFO|ERROR|WARN))
      source: "output"

  - labels:
      tag:
      stream:
      image_name:
      container:
      image_id:
      container_id:
      levelname:
